apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: nguyenduong2824/blogs:mongo-v1
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: admin
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: Duong_2824
        volumeMounts:
        - name: mongo-init
          mountPath: /docker-entrypoint-initdb.d/init-mongo.js
          subPath: init-mongo.js
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-init
        configMap:
          name: mongo-init-script
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
