apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
spec:
  capacity:
    storage: 5Gi
  storageClassName: nfs-storage
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.101.53
    path: "/mnt/data/elasticsearch"
